function lgraph = BiLSTM(NNnodes)
%% Create Deep Learning Network Architecture
% Script for creating the layers for a deep learning network with the following 
% properties:
%%
% 
%  Number of layers: 9
%  Number of connections: 8
%
%% 
% Run the script to create the layers in the workspace variable |layers|.
% 
% To learn more, see <matlab:helpview('deeplearning','generate_matlab_code') 
% Generate MATLAB Code From Deep Network Designer>.
% 
% Auto-generated by MATLAB on 2022-12-14 13:43:56
lgraph = layerGraph();
%% Create Array of Layers

layers = [
    sequenceInputLayer(NNnodes,"Name","sequence")
    bilstmLayer(256,"Name","bilstm_1")
    fullyConnectedLayer(128,"Name","fc_1")
    bilstmLayer(64,"Name","bilstm_2")
    fullyConnectedLayer(10,"Name","fc_2")
    fullyConnectedLayer(1,"Name","fc_3")
    regressionLayer("Name","regressionoutput")];

%% Plot Layers
lgraph = layers;
plot(layerGraph(layers));
end