function lgraph = FNN(NNnodes)
%% Create Deep Learning Network Architecture
% Script for creating the layers for a deep learning network with the following 
% properties:
%%
% 
%  Number of layers: 11
%  Number of connections: 10
%
%% 
% Run the script to create the layers in the workspace variable |layers|.
% 
% To learn more, see <matlab:helpview('deeplearning','generate_matlab_code') 
% Generate MATLAB Code From Deep Network Designer>.
% 
lgraph = layerGraph();
% Auto-generated by MATLAB on 2022-06-22 13:34:31
%% Create Array of Layers

layers = [
    sequenceInputLayer(NNnodes,"Name","sequence")
    fullyConnectedLayer(1024,"Name","fc_1")
    tanhLayer("Name","relu_1")
     fullyConnectedLayer(1024,"Name","fc_2")
    tanhLayer("Name","relu_2")
    fullyConnectedLayer(1,"Name","fc_7")
    regressionLayer("Name","regressionoutput")];
%% Plot Layers
lgraph = layers;
plot(layerGraph(layers));
end