function lgraph = FNN2()
%% Create Deep Learning Network Architecture
% Script for creating the layers for a deep learning network with the following 
% properties:
%%
% 
%  Number of layers: 16
%  Number of connections: 19
%
%% 
% Run the script to create the layers in the workspace variable |lgraph|.
% 
% To learn more, see <matlab:helpview('deeplearning','generate_matlab_code') 
% Generate MATLAB Code From Deep Network Designer>.
% 
% Auto-generated by MATLAB on 2022-06-22 10:06:33
%% Create Layer Graph
% Create the layer graph variable to contain the network layers.

lgraph = layerGraph();
%% Add Layer Branches
% Add the branches of the network to the layer graph. Each branch is a linear 
% array of layers.

tempLayers = [
    sequenceInputLayer(51*6,"Name","sequence")
    fullyConnectedLayer(51*6,"Name","fc_1")
    reluLayer("Name","relu_4")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = fullyConnectedLayer(51*6,"Name","fc_6");
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(51*6,"Name","addition_1")
    reluLayer("Name","relu_1")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = fullyConnectedLayer(51*6,"Name","fc_2");
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(51*6,"Name","addition_2")
    reluLayer("Name","relu_2")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = fullyConnectedLayer(51*6,"Name","fc_3");
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(51*6,"Name","addition_3")
    reluLayer("Name","relu_3")];
lgraph = addLayers(lgraph,tempLayers);

tempLayers = fullyConnectedLayer(51*6,"Name","fc_4");
lgraph = addLayers(lgraph,tempLayers);

tempLayers = [
    additionLayer(51*6,"Name","addition_4")
    fullyConnectedLayer(4,"Name","fc_5")
    regressionLayer("Name","regressionoutput")];
lgraph = addLayers(lgraph,tempLayers);

% clean up helper variable
clear tempLayers;
%% Connect Layer Branches
% Connect all the branches of the network to create the network graph.

lgraph = connectLayers(lgraph,"relu_4","fc_6");
lgraph = connectLayers(lgraph,"relu_4","addition_1/in2");
lgraph = connectLayers(lgraph,"fc_6","addition_1/in1");
lgraph = connectLayers(lgraph,"relu_1","fc_2");
lgraph = connectLayers(lgraph,"relu_1","addition_2/in2");
lgraph = connectLayers(lgraph,"fc_2","addition_2/in1");
lgraph = connectLayers(lgraph,"relu_2","fc_3");
lgraph = connectLayers(lgraph,"relu_2","addition_3/in2");
lgraph = connectLayers(lgraph,"fc_3","addition_3/in1");
lgraph = connectLayers(lgraph,"relu_3","fc_4");
lgraph = connectLayers(lgraph,"relu_3","addition_4/in2");
lgraph = connectLayers(lgraph,"fc_4","addition_4/in1");
%% Plot Layers

plot(lgraph);
end